### ISSUE TITLE
Choose functions runtime error

### ISSUE THREAD

**Issue by JonV2048** [RobTrew/prelude-applescript#1]
The app "macOS menu for choosing a set of Applescript Prelude functions to paste" compiles but has a runtime error saying the variable _ is not defined. 10.12.6

**Comment by RobTrew** [comment]
The Keyboard Maestro macro for choosing and pasting functions expects to find a local copy of this repository (at `~/prelude-applescript` by default).

I've added a message to the user - displayed when `~/prelude-applescript` isn't found.
